- type: job
  id: MarineEngineer
  name: job-name-marine-engineer
  description: job-description-marine-engineer
  playTimeTracker: JobMarineEngineer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Combat
    time: 7200 #2 hrs
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 7200 #2 hrs
  startingGear: MarineEngineerGear
  icon: "JobIconMarineEngineer"
  supervisors: job-supervisors-part-pc
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Engineering
  - Atmospherics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MarineEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    id: SecurityIDCard
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckIDMarksEngineer
