# Department
- type: department
  id: CommandMarine
  name: department-CommandMarine
  description: department-command-marine-description
  color: "#C3C3BD"
  weight: 80
  primary: false
  roles:
  - CompanyCommander
  - PlatoonCommander
  - MechPlatoonCommander
  - RoboPlatoonCommander
  - MarinePilot

- type: department
  id: Marine
  name: department-CommandMarine
  description: department-marine-description
  color: "#C3C3BD"
  weight: 70
  roles:
  - PlatoonCommander
  - Marine
  - MarineMedic
  - MarinePilot

- type: department
  id: RoboMarine
  name: department-RoboMarine
  description: department-robo-marine-description
  color: "#C3C3BD"
  weight: 60
  roles:
  - RoboPlatoonCommander
  - MilitaryBorg
  - MarineEngineer

- type: department
  id: MechMarine
  name: department-RoboMarine
  description: department-mech-marine-description
  color: "#C3C3BD"
  weight: 50
  roles:
  - MechPlatoonCommander
  - MechPilot


